#!/bin/bash
set -x  # Enable debug mode
exec > /var/log/qemu_hook.log 2>&1

VM_NAME="$1"
EVENT="$2"
PHASE="$3"

# Don't know why it MUST need, without it will stuck at attach-device...
RANDOM_HEX=$(printf "%04X\n" $(( RANDOM % 65536 )))
XML_FILENAME=/tmp/vm_${VM_NAME}_${RANDOM_HEX}_${EVENT}.xml
cat - > $XML_FILENAME
XML_CONTENT=$(cat $XML_FILENAME)
NEW_VM_NAME=`grep -P '[a-zA-Z0-9_]+(?=\</title)' -o $XML_FILENAME`

if [ "started" == "$EVENT" ]; then
    nohup sh /usr/local/libvirt/attach_detach_all.sh $VM_NAME &
fi
